local Notice = {
    {date = "2025-11-19", desc = "添加通用\n添加战斗勇士\n添加Blox Fruit\n添加一路向西\n添加战争大亨"},
    {date = "2025-11-19", desc = "Atomic免费版正式开始发布使用！"},
}
local LoadServer = {
    "战争大亨",
    "一路向西",
    "内脏与黑火药",
    "墨水游戏",
    "被遗弃",
    "Blox Fruit",
    "汉化中心",
    "Fisch",
    "Doors",
    "最强战场",
    "疯狂之城",
    "忍者传奇",
    "俄亥俄州",
    "驾驶帝国",
    "种植花园",
    "刀刃球",
    "压力",
    "在森林生存99夜",
    "在超市生活一周",
    "死铁轨",
    "汽车经销大亨",
    "生存七天",
    "柔术无限",
    "力量传奇",
    "极速传奇",
    "Da hood",
    "nico的机器人",
    "恐鬼症",
    "僵尸起义",
    "彩虹朋友2",
    "格蕾丝",
    "跳跃对决",
    "暴力区",
    "猎杀僵尸",
    "ST封锁战线",
    "躲避",
    "砍伐树木",
    "植物大战脑红",
    "建造动物园",
    "奇怪枪械",
    "偷走脑红",
    "避难所生活",
}
local LoadingSteps = {
    {text = "正在初始化系统...", progress = 0},
    {text = "检测运行环境...", progress = 8},
    {text = "加载核心模块...", progress = 18},
    {text = "初始化用户界面...", progress = 30},
    {text = "连接远程服务器...", progress = 45},
    {text = "验证用户权限...", progress = 60},
    {text = "下载游戏数据...", progress = 75},
    {text = "解析配置文件...", progress = 85},
    {text = "准备游戏列表...", progress = 95},
    {text = "中国最佳脚本！", progress = 100}
}
local Developers = {
    {name = "神仇", role = "主作者", desc = "项目负责人 · 核心架构", color = Color3.fromRGB(255, 100, 100)},
    {name = "麥克丰", role = "副作者", desc = "功能开发 · 代码优化", color = Color3.fromRGB(100, 255, 100)},
}
local List = {
    ["自动翻译"] = "https://raw.githubusercontent.com/123fa98/Xi_Pro/refs/heads/main/自动翻译.lua",
    ["力量传奇-Muscle Legends"] = "https://raw.githubusercontent.com/123fa98/Xi_Pro/refs/heads/main/力量传奇-Muscle Legends.lua",
    
}
return LoadingSteps, Notice, LoadServer, Developers, List 
